version: '3.8'
services:
  dev-db:
    image: postgres:latest
    container_name: dev-db
    command: postgres -c listen_addresses=0.0.0.0
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - mealtime
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready -U supertokens_user']
      interval: 5s
      timeout: 5s
      retries: 5
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    container_name: supertokens
    depends_on:
      - dev-db
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: '${DATABASE_URL_DOCKER}'
    networks:
      - mealtime
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5
  test-db:
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - mealtime
  nodejs:
    depends_on:
      - supertokens
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200
      - 3333:3333
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mealtime
  calypso:
    build:
      context: ./golang
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/calypso
        port: 3001
    environment:
      - APP_NAME=calypso
    ports:
      - 8001:3000
    restart: on-failure
    volumes:
      - ./golang:/usr/src/app
    networks:
      - mealtime
  echo:
    build:
      context: ./golang
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/echo
        port: 3001
    environment:
      - APP_NAME=echo
    ports:
      - 8002:3000
    restart: on-failure
    volumes:
      - ./golang:/usr/src/app
    networks:
      - mealtime

networks:
  mealtime:
    driver: bridge
