version: '3.8'
services:
  dev-db:
    image: postgres:12
    container_name: dev-db
    command: postgres -c listen_addresses=0.0.0.0 -c port=5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - mealtime
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready -U supertokens_user']
      interval: 5s
      timeout: 5s
      retries: 5
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    container_name: supertokens
    depends_on:
      - nodejs
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: 'postgresql://postgres:123@dev-db:5432/nest?schema=public'
    networks:
      - mealtime
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5
  nodejs:
    depends_on:
      - dev-db
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200
      - 3333:3333
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mealtime

networks:
  mealtime:
    driver: bridge
