version: '3.8'
services:
  dev-db:
    image: postgres:12
    container_name: dev-db
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - mealtime
    restart: unless-stopped
    # healthcheck:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  dev-db-healthcheck:
    image: postgres:12
    container_name: dev-db-healthcheck
    command: ["pg_isready", "-U", "${POSTGRES_USER}"]
    depends_on:
      - dev-db
    networks:
      - mealtime
    restart: unless-stopped

networks:
  mealtime:
    driver: bridge
