version: '3'

services:
  db:
    image: postgres:16.3-alpine
    container_name: db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_user_pass
    ports:
      - '6033:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
