version: 2.1
jobs:
  lint:
    machine:
      image: ubuntu-2204:2022.04.2
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      # look for existing cache and restore if found
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules
      - run:
          name: Run tests
          command: |
            yarn lint
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules
      - run:
          name: Run tests
          command: |
            yarn build
  
  test:
    machine:
      image: ubuntu-2204:2022.04.2
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      # look for existing cache and restore if found
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules
      - run:
          name: Run tests
          command: |
            yarn ci:test
  e2e:
    machine:
      image: ubuntu-2204:2022.04.2
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      # look for existing cache and restore if found
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules
      - run:
          name: Run tests
          command: |
            yarn e2e
workflows:
  CI_Tests:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - e2e:
          requires:
            - test
