version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/node:16.3.0
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      # look for existing cache and restore if found
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: |
            yarn lint
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/*
            - cypress/*
  build:
    docker:
      - image: circleci/node:16.3.0
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            yarn build

  test:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      - run:
          name: Install docker-compose
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      # look for existing cache and restore if found
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: |
            yarn ci:test
  e2e:
    docker:
      - image: circleci/node:16.3.0
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      # look for existing cache and restore if found
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run e2e tests
          command: |
            yarn ci:e2e
workflows:
  CI_Tests:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - e2e:
          requires:
            - test
