version: 2.1
jobs:
  run_tests:
    machine:
      image: ubuntu-2204:2022.04.2
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      # Install via apk on alpine based images
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      - run:
          name: Run tests
          command: |
            yarn test
workflows:
  CI_Tests:
    jobs:
      - run_tests