version: 2.1
jobs:

  test:
    machine:
      image: ubuntu-2204:2022.04.2
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      # look for existing cache and restore if found
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: |
            node --version
            yarn ci:test
  e2e:
    machine:
      image: ubuntu-2204:2022.04.2
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      # look for existing cache and restore if found
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run e2e tests
          command: |
            yarn ci:e2e
workflows:
  CI_Tests:
    jobs:

      - test

      - e2e:
          requires:
            - test
