version: 2.1
jobs:
  run_tests:
    docker:
      - image: cimg/node:lts
    working_directory: ~/BHelpful
    steps:
      - checkout:
          path: ~/BHelpful
      - run:
          name: Install dependencies
          command: |
            yarn install --ignore-engines
      - run:
          name: Run tests
          command: |
            yarn test
      - setup_remote_docker:
          version: 20.10.14
workflows:
  CI_Tests:
    jobs:
      - run_tests