name: Minor
description: Create a minor feature
title: "[Minor]: "
labels: [MINOR]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a new minor feature to improve our product!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short description of the feature
      placeholder: "Describe the feature"
    validations:
      required: true
  - type: textarea
    id: ux
    attributes:
      label: UX
      description: Design of the feature. If no design is available leave questions for UX here.
      placeholder: Implement the following design...
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: The criteria for which the feature will be accepted in a Pull Request.
      placeholder: The implementation should have ...
      value: |
        - [ ] 
    validations:
      required: true
  - type: textarea
    id: comments-questions
    attributes:
      label: Comments / questions
      description: Any comments or questions relating the story.
      placeholder: We should devide this into sub-tasks...
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/BHelpful/Mealplanr/blob/master/docs/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
