name: Sync

on:
  push:
    branches:
      - prod

jobs:
  branch-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          git config --global user.name 'Sync from prod'
          git config --global user.email 'andreasgdp@gmail.com'

      - name: Check if there are changes between prod and master
        id: check_diff
        run: |
          git fetch origin master
          git diff --quiet origin/master..origin/prod || (echo "changes detected" && exit 0) || exit 1

      - name: Push changes to master when prod is updated
        run: |
          git checkout master 
          git merge prod
          git push origin master
