name: Sync

on:
  push:
    branches:
      - prod

jobs:
  branch-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Check if there are changes between prod and master
        id: check_diff
        run: |
          git fetch origin master
          git fetch origin prod
          DIFF=$(git diff --name-only origin/master..origin/prod)
          if [ "$DIFF" != "" ]; then
            echo "changes detected"
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
          else
            echo "no changes detected"
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Reset sync branch
        run: |
          git fetch origin prod:prod
          git reset --hard prod

      - name: Create Pull Request
        id: cpr
        if: steps.check_diff.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          branch: prod-sync
          base: master
          title: "Sync changes from prod to master"
          body: "This PR is automatically generated to sync changes from prod to master."
          labels: "sync,automated pr"

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge

      - name: Auto approve
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr review --approve "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
